#!/bin/bash
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/sbin
#clean dns cache
	dscacheutil -flushcache
#get gateway
	#ovpn
    vpngw=`netstat -nr | grep ^0/1 | grep -P 'tun|tap' | head -1 | awk '{print $2}'`
	#noneovpn
    if [ -z ${VPNGW} ]; then
		vpngw=`netstat -nr | grep ^default | grep ppp | head -1 | awk '{print $2}'`
    fi
	#get oldgw	
    oldgw=`netstat -nr | grep -P '^default|^0/1' | grep -v $(echo ${VPNGW}) | head -1 | awk '{print $2}'`

	#set the gateway below
	#DO NOT uncomment them if nothing goes wrong!!!
	#oldgw=192.168.2.1
	#vpngw=192.168.0.1
#log
	echo $oldgw > /tmp/vpn_oldgw
	echo $vpngw > /tmp/vpn_vpngw
source /usr/local/etc/vpnup.sh
source /usr/local/etc/ipupadd.sh
#change default gw
	route delete 0/1 $vpngw
	route delete 128.0/1 $vpngw
	route delete default $vpngw
	route delete default $oldgw
	route add default $oldgw
